<?php

namespace DropstockBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Site2Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Site2Repository extends EntityRepository
{
}
