DropstockBundle\Entity\Site:
    type: entity
    table: null
    repositoryClass: DropstockBundle\Repository\SiteRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        url:
            type: text
        platform:
            type: string
            length: 255
        status:
            type: string
            length: 255
        checked:
            type: datetime
        token:
            type: string
            length: 255
    lifecycleCallbacks: {  }
