DropstockBundle\Entity\Site:
    type: entity
    table: null
    repositoryClass: DropstockBundle\Repository\SiteRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        url:
            type: text
        platform:
            type: string
            length: 255
            nullable: true
        status:
            type: string
            length: 255
            nullable: true
        checked:
            type: datetime
            nullable: true
        token:
            type: string
            length: 255
            nullable: true
        crypt:
            type: string
            length: 255
            nullable: true
        modules:
            type: array
            nullable: true
        data:
            type: json_array
            nullable: true
    lifecycleCallbacks: {  }
